name: GitHub Actions Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Golang
      uses: actions/setup-go@v4
      with:
        go-version: '^1.22'
    - name: Build
      shell: cmd
      run: .\make.bat all
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: 'latest'
        title: 'latest'
        prerelease: false
        files: |
          dist/*
